accumulate_grad_batches: 8
amp_backend: native
amp_level: O2
args: !!python/object:argparse.Namespace
  accumulate_grad_batches: 8
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  base_model_dir: ../models/
  batch_size: 8
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  data_dir: ../data/lm_chess/uci
  default_root_dir: null
  deterministic: false
  distributed_backend: null
  early_stop_callback: false
  fast_dev_run: false
  feature_redraw: 1000
  generalized_attention: false
  gpus: &id001 !!python/name:pytorch_lightning.trainer.trainer._gpus_arg_default ''
  gradient_clip_val: 0
  init_lr: 0.0005
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  local_attn_heads: 6
  local_window_size: 50
  log_gpu_memory: null
  log_save_interval: 100
  logger: true
  max_epochs: 10
  max_steps: null
  min_epochs: 1
  min_steps: null
  model_name: lm_ts_200000_layer_12_head_12_emb_768_rbs_64_seed_42
  model_type: transformer
  n_embd: 768
  n_head: 12
  n_hid: 768
  n_layer: 12
  n_positions: 512
  num_buckets: null
  num_hashes: 1
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  num_training_steps: 31250
  num_workers: 2
  oracle: false
  other_eval: true
  overfit_batches: 0.0
  overfit_pct: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: 1
  rap_no_grad: false
  rap_prob: 0.0
  real_batch_size: 64
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  rnn_dropout: 0.2
  rnn_type: lstm
  row_log_interval: 50
  save_dir: ../models/
  seed: 42
  stride_size: null
  sync_batchnorm: false
  terminate_on_nan: false
  test_percent_check: null
  tpu_cores: *id001
  track_grad_norm: -1
  train_percent_check: null
  train_size: 200000
  truncated_bptt_steps: null
  val_check_interval: 1.0
  val_percent_check: null
  vocab_dir: ../data/lm_chess/vocab/uci
  weights_save_path: null
  weights_summary: top
  window_size: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
base_model_dir: ../models/
batch_size: 8
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: ../data/lm_chess/uci
default_root_dir: null
deterministic: false
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
feature_redraw: 1000
generalized_attention: false
gradient_clip_val: 0
init_lr: 0.0005
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
local_attn_heads: 6
local_window_size: 50
log_gpu_memory: null
log_save_interval: 100
logger: true
max_epochs: 10
max_steps: null
min_epochs: 1
min_steps: null
model_name: lm_ts_200000_layer_12_head_12_emb_768_rbs_64_seed_42
model_type: transformer
n_embd: 768
n_head: 12
n_hid: 768
n_layer: 12
n_positions: 512
num_buckets: null
num_hashes: 1
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_training_steps: 31250
num_workers: 2
oracle: false
other_eval: true
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
rap_no_grad: false
rap_prob: 0.0
real_batch_size: 64
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
rnn_dropout: 0.2
rnn_type: lstm
row_log_interval: 50
save_dir: ../models/
seed: 42
stride_size: null
sync_batchnorm: false
terminate_on_nan: false
test_percent_check: null
track_grad_norm: -1
train_percent_check: null
train_size: 200000
truncated_bptt_steps: null
val_check_interval: 1.0
val_percent_check: null
vocab_dir: ../data/lm_chess/vocab/uci
weights_save_path: null
weights_summary: top
window_size: null
